2024-03-04 18:19:43,224 (388875/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-03-04 18:19:43,224 (388875/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-03-04 18:19:43,226 (388875/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/usr/lib/python3.11/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/psycopg/connection.py", line 749, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-03-04 18:20:26,231 (389657/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-03-04 18:20:26,231 (389657/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-03-04 18:21:17,751 (389657/MainThread) pgcli.pgexecute ERROR - sql: 'create table User (', error: SyntaxError('syntax error at or near "User"\nLINE 1: create table User (\n                     ^')
2024-03-04 18:21:17,752 (389657/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "User"\nLINE 1: create table User (\n                     ^\n'
2024-03-04 18:21:20,944 (389657/MainThread) pgcli.pgexecute ERROR - sql: 'create table User (', error: SyntaxError('syntax error at or near "User"\nLINE 1: create table User (\n                     ^')
2024-03-04 18:21:20,945 (389657/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "User"\nLINE 1: create table User (\n                     ^\n'
2024-03-04 18:24:22,328 (393349/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-03-04 18:24:22,328 (393349/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-03-04 18:24:40,516 (393806/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-03-04 18:24:40,516 (393806/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-03-04 18:27:36,063 (393806/MainThread) pgcli.main ERROR - sql: '\\dt', error: StopIteration()
2024-03-04 18:27:36,064 (393806/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/main.py", line 749, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/main.py", line 1093, in _evaluate_command\n    formatted = format_output(\n                ^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/main.py", line 1672, in format_output\n    first_line = next(formatted)\n                 ^^^^^^^^^^^^^^^\nStopIteration\n'
2024-03-04 18:27:41,349 (393806/MainThread) pgcli.main ERROR - sql: '\\dt', error: StopIteration()
2024-03-04 18:27:41,350 (393806/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/main.py", line 749, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/main.py", line 1093, in _evaluate_command\n    formatted = format_output(\n                ^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/main.py", line 1672, in format_output\n    first_line = next(formatted)\n                 ^^^^^^^^^^^^^^^\nStopIteration\n'
2024-03-04 18:29:42,166 (393806/MainThread) pgcli.pgexecute ERROR - sql: 'create table User (\nusername VARCHAR(50) not null,\nemail varchar(100) not null,\npassword varchar(100) not null,\nuserid int generated always as identity)', error: SyntaxError('syntax error at or near "User"\nLINE 1: create table User (\n                     ^')
2024-03-04 18:29:42,167 (393806/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "User"\nLINE 1: create table User (\n                     ^\n'
2024-03-04 18:30:06,963 (393806/MainThread) pgcli.pgexecute ERROR - sql: 'create table User(\nusername VARCHAR(50) not null,\nemail varchar(100) not null,\npassword varchar(100) not null,\nuserid int generated always as identity)', error: SyntaxError('syntax error at or near "User"\nLINE 1: create table User(\n                     ^')
2024-03-04 18:30:06,965 (393806/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "User"\nLINE 1: create table User(\n                     ^\n'
2024-03-04 18:30:20,168 (393806/MainThread) pgcli.pgexecute ERROR - sql: 'create table User(\nusername VARCHAR(50) not null,\nemail varchar(100) not null,\npassword varchar(100) not null,\nuserid int generated always as identity)', error: SyntaxError('syntax error at or near "User"\nLINE 1: create table User(\n                     ^')
2024-03-04 18:30:20,169 (393806/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "User"\nLINE 1: create table User(\n                     ^\n'
2024-03-04 18:30:44,652 (393806/MainThread) pgcli.pgexecute ERROR - sql: 'create table User(\nusername VARCHAR(50) not null,\nemail varchar(100) not null,\npassword varchar(100) not null,\nuserid int generated always as identity\nprimary key(userid))', error: SyntaxError('syntax error at or near "User"\nLINE 1: create table User(\n                     ^')
2024-03-04 18:30:44,653 (393806/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "User"\nLINE 1: create table User(\n                     ^\n'
2024-03-04 18:32:51,619 (393806/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE TABLE User(username VARCHAR(100) NOT NULL )', error: SyntaxError('syntax error at or near "User"\nLINE 1: CREATE TABLE User(username VARCHAR(100) NOT NULL )\n                     ^')
2024-03-04 18:32:51,621 (393806/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "User"\nLINE 1: CREATE TABLE User(username VARCHAR(100) NOT NULL )\n                     ^\n'
2024-03-04 18:33:17,725 (393806/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE TABLE user(username VARCHAR(100) NOT NULL )', error: SyntaxError('syntax error at or near "user"\nLINE 1: CREATE TABLE user(username VARCHAR(100) NOT NULL )\n                     ^')
2024-03-04 18:33:17,726 (393806/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "user"\nLINE 1: CREATE TABLE user(username VARCHAR(100) NOT NULL )\n                     ^\n'
2024-03-04 18:35:32,385 (393806/MainThread) pgcli.pgexecute ERROR - sql: 'create table User(\nusername VARCHAR(50) not null,\nemail varchar(100) not null,\npassword varchar(100) not null,\nuserid int generated always as identity,\nprimary key(userid))', error: SyntaxError('syntax error at or near "User"\nLINE 1: create table User(\n                     ^')
2024-03-04 18:35:32,386 (393806/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "User"\nLINE 1: create table User(\n                     ^\n'
2024-03-04 18:36:58,091 (393806/MainThread) pgcli.pgexecute ERROR - sql: 'create table user(\nusername VARCHAR(50) not null,\nemail varchar(100) not null,\npassword varchar(100) not null,\nuserid int generated always as identity,\nprimary key(userid)\n)', error: SyntaxError('syntax error at or near "user"\nLINE 1: create table user(\n                     ^')
2024-03-04 18:36:58,092 (393806/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "user"\nLINE 1: create table user(\n                     ^\n'
2024-03-04 18:37:07,003 (393806/MainThread) pgcli.main ERROR - sql: '\\dt', error: StopIteration()
2024-03-04 18:37:07,003 (393806/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/main.py", line 749, in execute_command\n    output, query = self._evaluate_command(text)\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/main.py", line 1093, in _evaluate_command\n    formatted = format_output(\n                ^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/main.py", line 1672, in format_output\n    first_line = next(formatted)\n                 ^^^^^^^^^^^^^^^\nStopIteration\n'
2024-03-04 18:37:17,823 (400993/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-03-04 18:37:17,824 (400993/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-03-04 18:37:24,835 (400993/MainThread) pgcli.pgexecute ERROR - sql: 'create table user(\nusername VARCHAR(50) not null,\nemail varchar(100) not null,\npassword varchar(100) not null,\nuserid int generated always as identity,\nprimary key(userid)\n)', error: SyntaxError('syntax error at or near "user"\nLINE 1: create table user(\n                     ^')
2024-03-04 18:37:24,836 (400993/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "user"\nLINE 1: create table user(\n                     ^\n'
2024-03-04 18:40:15,927 (400993/MainThread) pgcli.pgexecute ERROR - sql: 'create table user(\nusername VARCHAR(50) not null,\nemail varchar(100) not null,\npassword varchar(100) not null,\nuserid int generated always as identity,\nprimary key(userid)\n)', error: SyntaxError('syntax error at or near "user"\nLINE 1: create table user(\n                     ^')
2024-03-04 18:40:15,928 (400993/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "user"\nLINE 1: create table user(\n                     ^\n'
2024-03-04 18:42:01,525 (400993/MainThread) pgcli.pgexecute ERROR - sql: 'create table user (\nuserid int generated always as identity,\nusername varchar(100) not null,\nemail varchar(100) not null,\npassword varchar(100) not null,\nprimary key(userid)\n)', error: SyntaxError('syntax error at or near "user"\nLINE 1: create table user (\n                     ^')
2024-03-04 18:42:01,526 (400993/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "user"\nLINE 1: create table user (\n                     ^\n'
2024-03-04 18:44:30,594 (400993/MainThread) pgcli.pgexecute ERROR - sql: 'drop table plannerpuser', error: UndefinedTable('table "plannerpuser" does not exist')
2024-03-04 18:44:30,595 (400993/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: table "plannerpuser" does not exist\n'
2024-03-04 18:44:55,067 (400993/MainThread) pgcli.pgexecute ERROR - sql: 'create table planerp_user(\nuser_id int generated always as identity,\nusername varchar(100) not null,\nemail varchar(100) not null,\npassword varchar(100) not null,\nprimary key(userid)\n)', error: UndefinedColumn('column "userid" named in key does not exist\nLINE 6: primary key(userid)\n        ^')
2024-03-04 18:44:55,068 (400993/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "userid" named in key does not exist\nLINE 6: primary key(userid)\n        ^\n'
2024-03-04 19:02:44,279 (400993/MainThread) pgcli.pgexecute ERROR - sql: 'create table planerp_material(\nmaterial_id int generated always as identity,\nproject_id int,\nname varchar(100) not null,\ntype varchar(50) null,\ncategory varchar(50) null,\ndescription varchar (2000) null,\nprice float not null,\nsuplier varchar(100) not null,\nsuplier_link varchar (1000) null,\n\nprimary key(material_id),\nconstraint fk_project_id foreign key(project_id) references planerp_project(project_id) on delete set null\n)', error: InvalidForeignKey('there is no unique constraint matching given keys for referenced table "planerp_project"')
2024-03-04 19:02:44,279 (400993/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.InvalidForeignKey: there is no unique constraint matching given keys for referenced table "planerp_project"\n'
2024-03-04 19:06:06,477 (400993/MainThread) pgcli.pgexecute ERROR - sql: 'create table planerp_resource_doc(\nresource_doc_id int generated always as identity,\ntitle varchar(100) not null,\nurl varchar(1500) null,\ndescription varchar (2000) null,\n)', error: SyntaxError('syntax error at or near ")"\nLINE 6: )\n        ^')
2024-03-04 19:06:06,478 (400993/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near ")"\nLINE 6: )\n        ^\n'
2024-03-04 19:06:30,745 (400993/MainThread) pgcli.pgexecute ERROR - sql: 'create table planerp_resource_doc(\nresource_doc_id int generated always as identity,\ntitle varchar(100) not null,\nurl varchar(1500) null,\ndescription varchar(2000) null,\n)', error: SyntaxError('syntax error at or near ")"\nLINE 6: )\n        ^')
2024-03-04 19:06:30,745 (400993/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near ")"\nLINE 6: )\n        ^\n'
2024-03-04 19:09:10,281 (400993/MainThread) pgcli.pgexecute ERROR - sql: 'create table planerp_resource_doc(\nresource_doc_id int generated always as identity,\nmaterial_id int,\ntitle varchar(100) not null,\nurl varchar(1500) null,\ndescription varchar(2000) null\n\nprimary key(resource_doc_id),\nconstraint fk_material_id foreign key (material_id) references planerp_material(material_id)\n)', error: SyntaxError('syntax error at or near "("\nLINE 8: primary key(resource_doc_id),\n                   ^')
2024-03-04 19:09:10,283 (400993/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "("\nLINE 8: primary key(resource_doc_id),\n                   ^\n'
2024-03-05 13:08:53,688 (194745/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-03-05 13:08:53,689 (194745/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-03-05 13:08:53,692 (194745/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/usr/lib/python3.11/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/psycopg/connection.py", line 749, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-03-05 13:08:57,949 (194981/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-03-05 13:08:57,949 (194981/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-03-05 13:14:01,265 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'call GetMaterialById(1)', error: UndefinedTable('relation "planerp_material" does not exist\nLINE 1: select * from planerp_material where material_id = Id\n                      ^\nQUERY:  select * from planerp_material where material_id = Id\nCONTEXT:  PL/pgSQL function getmaterialbyid(integer) line 3 at SQL statement')
2024-03-05 13:14:01,266 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedTable: relation "planerp_material" does not exist\nLINE 1: select * from planerp_material where material_id = Id\n                      ^\nQUERY:  select * from planerp_material where material_id = Id\nCONTEXT:  PL/pgSQL function getmaterialbyid(integer) line 3 at SQL statement\n'
2024-03-05 13:16:02,717 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'call GetMaterialById(1)', error: SyntaxError('query has no destination for result data\nHINT:  If you want to discard the results of a SELECT, use PERFORM instead.\nCONTEXT:  PL/pgSQL function getmaterialbyid(integer) line 3 at SQL statement')
2024-03-05 13:16:02,718 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: query has no destination for result data\nHINT:  If you want to discard the results of a SELECT, use PERFORM instead.\nCONTEXT:  PL/pgSQL function getmaterialbyid(integer) line 3 at SQL statement\n'
2024-03-05 13:24:58,542 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace function GetMaterialById(Id int) returns setof public.planerp.material language plpgsql as $$\nbegin\nselect * from planerp_material where material_id = Id;\nend;$$', error: FeatureNotSupported('cross-database references are not implemented: public.planerp.material')
2024-03-05 13:24:58,543 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.FeatureNotSupported: cross-database references are not implemented: public.planerp.material\n'
2024-03-05 13:25:11,084 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace function GetMaterialById(Id int) returns setof public.planerp_material language plpgsql as $$\nbegin\nselect * from planerp_material where material_id = Id;\nend;$$', error: WrongObjectType('cannot change routine kind\nDETAIL:  "getmaterialbyid" is a procedure.')
2024-03-05 13:25:11,085 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.WrongObjectType: cannot change routine kind\nDETAIL:  "getmaterialbyid" is a procedure.\n'
2024-03-05 13:26:17,509 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace function GetMaterialById(Id int) return public.planerp_material language plpgsql as $$\nbegin\nselect * from planerp_material where material_id = Id;\nend;$$', error: SyntaxError('syntax error at or near "language"\nLINE 1: ...terialById(Id int) return public.planerp_material language p...\n                                                             ^')
2024-03-05 13:26:17,509 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "language"\nLINE 1: ...terialById(Id int) return public.planerp_material language p...\n                                                             ^\n'
2024-03-05 13:26:30,264 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace function GetMaterialById(Id int) return setof public.planerp_material language plpgsql as $$\nbegin\nselect * from planerp_material where material_id = Id;\nend;$$', error: SyntaxError('syntax error at or near "public"\nLINE 1: ...ace function GetMaterialById(Id int) return setof public.pla...\n                                                             ^')
2024-03-05 13:26:30,264 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "public"\nLINE 1: ...ace function GetMaterialById(Id int) return setof public.pla...\n                                                             ^\n'
2024-03-05 13:26:46,069 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace function GetMaterialById(Id int) returns public.planerp_material language plpgsql as $$\nbegin\nselect * from planerp_material where material_id = Id;\nend;$$', error: InvalidFunctionDefinition('cannot change return type of existing function\nHINT:  Use DROP FUNCTION getmaterialbyid(integer) first.')
2024-03-05 13:26:46,070 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.InvalidFunctionDefinition: cannot change return type of existing function\nHINT:  Use DROP FUNCTION getmaterialbyid(integer) first.\n'
2024-03-05 13:29:11,683 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'call GetMaterialById(1)', error: WrongObjectType('getmaterialbyid(integer) is not a procedure\nLINE 1: call GetMaterialById(1)\n             ^\nHINT:  To call a function, use SELECT.')
2024-03-05 13:29:11,684 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.WrongObjectType: getmaterialbyid(integer) is not a procedure\nLINE 1: call GetMaterialById(1)\n             ^\nHINT:  To call a function, use SELECT.\n'
2024-03-05 13:29:34,008 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'select GetMaterialById(1)', error: SyntaxError('query has no destination for result data\nHINT:  If you want to discard the results of a SELECT, use PERFORM instead.\nCONTEXT:  PL/pgSQL function getmaterialbyid(integer) line 3 at SQL statement')
2024-03-05 13:29:34,009 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: query has no destination for result data\nHINT:  If you want to discard the results of a SELECT, use PERFORM instead.\nCONTEXT:  PL/pgSQL function getmaterialbyid(integer) line 3 at SQL statement\n'
2024-03-05 13:29:47,728 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'perform GetMaterialById(1)', error: SyntaxError('syntax error at or near "perform"\nLINE 1: perform GetMaterialById(1)\n        ^')
2024-03-05 13:29:47,729 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "perform"\nLINE 1: perform GetMaterialById(1)\n        ^\n'
2024-03-05 13:30:13,259 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'select GetMaterialById(Id => 1)', error: SyntaxError('query has no destination for result data\nHINT:  If you want to discard the results of a SELECT, use PERFORM instead.\nCONTEXT:  PL/pgSQL function getmaterialbyid(integer) line 3 at SQL statement')
2024-03-05 13:30:13,260 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: query has no destination for result data\nHINT:  If you want to discard the results of a SELECT, use PERFORM instead.\nCONTEXT:  PL/pgSQL function getmaterialbyid(integer) line 3 at SQL statement\n'
2024-03-05 13:30:57,529 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'select "GetMaterialById"(1)', error: UndefinedFunction('function GetMaterialById(integer) does not exist\nLINE 1: select "GetMaterialById"(1)\n               ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.')
2024-03-05 13:30:57,529 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedFunction: function GetMaterialById(integer) does not exist\nLINE 1: select "GetMaterialById"(1)\n               ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n'
2024-03-05 13:31:12,527 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'select GetMaterialById(1)', error: SyntaxError('query has no destination for result data\nHINT:  If you want to discard the results of a SELECT, use PERFORM instead.\nCONTEXT:  PL/pgSQL function getmaterialbyid(integer) line 3 at SQL statement')
2024-03-05 13:31:12,528 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: query has no destination for result data\nHINT:  If you want to discard the results of a SELECT, use PERFORM instead.\nCONTEXT:  PL/pgSQL function getmaterialbyid(integer) line 3 at SQL statement\n'
2024-03-05 13:32:21,784 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace function GetMaterialById(Id int) returns public.planerp_material language plpgsql as $$\nbegin\nreturn (select * from planerp_material where material_id = Id;)\nend;$$', error: SyntaxError('mismatched parentheses at or near ";"\nLINE 3: ...urn (select * from planerp_material where material_id = Id;)\n                                                                     ^')
2024-03-05 13:32:21,784 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: mismatched parentheses at or near ";"\nLINE 3: ...urn (select * from planerp_material where material_id = Id;)\n                                                                     ^\n'
2024-03-05 13:32:31,474 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace function GetMaterialById(Id int) returns public.planerp_material language plpgsql as $$\nbegin\nreturn (select * from planerp_material where material_id = Id)\nend;$$', error: SyntaxError('syntax error at end of input\nLINE 4: end;$$\n            ^')
2024-03-05 13:32:31,474 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 4: end;$$\n            ^\n'
2024-03-05 13:32:48,612 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'select GetMaterialById(1)', error: SyntaxError('subquery must return only one column\nLINE 1: (select * from planerp_material where material_id = Id)\n        ^\nQUERY:  (select * from planerp_material where material_id = Id)\nCONTEXT:  PL/pgSQL function getmaterialbyid(integer) line 3 at RETURN')
2024-03-05 13:32:48,612 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: subquery must return only one column\nLINE 1: (select * from planerp_material where material_id = Id)\n        ^\nQUERY:  (select * from planerp_material where material_id = Id)\nCONTEXT:  PL/pgSQL function getmaterialbyid(integer) line 3 at RETURN\n'
2024-03-05 13:34:56,434 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace function GetMaterialById(Id int) returns public.planerp_material language plpgsql as $$\nbegin\nreturn query select * from planerp_material where material_id = Id;\nend;$$', error: DatatypeMismatch('cannot use RETURN QUERY in a non-SETOF function\nLINE 3: return query select * from planerp_material where material_i...\n        ^')
2024-03-05 13:34:56,434 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.DatatypeMismatch: cannot use RETURN QUERY in a non-SETOF function\nLINE 3: return query select * from planerp_material where material_i...\n        ^\n'
2024-03-05 13:55:26,546 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace function GetMaterialById(Id int) returns setof public.planerp_material language plpgsql as $$\nbegin\nreturn query select * from planerp_material where material_id = Id;\nend;$$', error: InvalidFunctionDefinition('cannot change return type of existing function\nHINT:  Use DROP FUNCTION getmaterialbyid(integer) first.')
2024-03-05 13:55:26,547 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.InvalidFunctionDefinition: cannot change return type of existing function\nHINT:  Use DROP FUNCTION getmaterialbyid(integer) first.\n'
2024-03-05 13:56:29,661 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'call GetMaterialById(1)', error: WrongObjectType('getmaterialbyid(integer) is not a procedure\nLINE 1: call GetMaterialById(1)\n             ^\nHINT:  To call a function, use SELECT.')
2024-03-05 13:56:29,661 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.WrongObjectType: getmaterialbyid(integer) is not a procedure\nLINE 1: call GetMaterialById(1)\n             ^\nHINT:  To call a function, use SELECT.\n'
2024-03-05 13:56:58,122 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'select * from GeMaterialById(1)', error: UndefinedFunction('function gematerialbyid(integer) does not exist\nLINE 1: select * from GeMaterialById(1)\n                      ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.')
2024-03-05 13:56:58,123 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedFunction: function gematerialbyid(integer) does not exist\nLINE 1: select * from GeMaterialById(1)\n                      ^\nHINT:  No function matches the given name and argument types. You might need to add explicit type casts.\n'
2024-03-05 19:59:38,054 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'call getmaterialbyid(3)', error: WrongObjectType('getmaterialbyid(integer) is not a procedure\nLINE 1: call getmaterialbyid(3)\n             ^\nHINT:  To call a function, use SELECT.')
2024-03-05 19:59:38,059 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.WrongObjectType: getmaterialbyid(integer) is not a procedure\nLINE 1: call getmaterialbyid(3)\n             ^\nHINT:  To call a function, use SELECT.\n'
2024-03-05 20:30:14,560 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'create or replace function GetMaterial() returns setof public.planterp_material\nlanguage plpgsql as\n$$\nbegin\nreturn query select * from planerp_material;\nend;\n$$', error: UndefinedObject('type "public.planterp_material" does not exist')
2024-03-05 20:30:14,561 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedObject: type "public.planterp_material" does not exist\n'
2024-03-05 20:39:43,811 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'alter table planerp_material rename column materialid to material_id', error: UndefinedColumn('column "materialid" does not exist')
2024-03-05 20:39:43,812 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "materialid" does not exist\n'
2024-03-05 20:43:36,929 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'alter table planerp_material rename column material_id to MaterialId', error: UndefinedColumn('column "material_id" does not exist')
2024-03-05 20:43:36,929 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "material_id" does not exist\n'
2024-03-05 20:44:35,149 (194981/MainThread) pgcli.pgexecute ERROR - sql: 'alter table planerp_material rename column suplier_id to suplierid', error: UndefinedColumn('column "suplier_id" does not exist')
2024-03-05 20:44:35,149 (194981/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/usr/lib/python3.11/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/usr/lib/python3.11/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedColumn: column "suplier_id" does not exist\n'
